<?php
namespace app\common;
/**
 *PHPer:liu
 *time:2018/1/5/005 10:42
 *motto:Buddha bless, never bug!
 */


use think\Controller;
use think\Request;
use think\Session;

class Base extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        //在公共控制器初始化的方法中,创建常量判断用户是否登录
        define('ADMIN_ID',Session::get('username'));
    }

    //判断用户是否登录 后台入口文件调用
    protected function isLogin(){
        if (is_null(ADMIN_ID)){
            $this->error('用户未登录,请登录~','index/login/index');
        }
    }


    public function __construct(Request $request = null)
    {
        parent::__construct($request);
        $this->isLogin();
    }
}
